# Generated by Django 4.2.5 on 2023-09-20 04:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("item", "0002_alter_catergory_options_item"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Catergory",
            new_name="Category",
        ),
        migrations.RenameField(
            model_name="item",
            old_name="catergory",
            new_name="category",
        ),
    ]
