# Generated by Django 4.2.5 on 2023-09-19 23:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Catergory",
        ),
    ]
